// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz1p7Zo70eNwvgP9FOuhbZ1oAJG31dE', // Get actual web API key from Firebase Console → Project Settings → Web apps
    appId: '1:387032593007:android:6ddd689db4a22fd2d0939a', // Get actual web app ID from Firebase Console
    messagingSenderId: '387032593007', // Get actual sender ID from Firebase Console → Project Settings → Cloud Messaging
    projectId: 'neurolearn-f9f54',
    authDomain: 'neurolearn.firebaseapp.com',
    storageBucket: 'neurolearn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz1p7Zo70eNwvgP9FOuhbZ1oAJG31dE', // Get actual Android API key from Firebase Console → Project Settings → Android apps
    appId: '1:387032593007:android:6ddd689db4a22fd2d0939a', // Get actual Android app ID from Firebase Console
    messagingSenderId: '387032593007',
    projectId: 'neurolearn-f9f54',
    storageBucket: 'neurolearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz1p7Zo70eNwvgP9FOuhbZ1oAJG31dE', // Get actual iOS API key from Firebase Console → Project Settings → iOS apps
    appId: '1:387032593007:android:6ddd689db4a22fd2d0939a', // Get actual iOS app ID from Firebase Console
    messagingSenderId: '387032593007',
    projectId: 'neurolearn-f9f54',
    storageBucket: 'neurolearn.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz1p7Zo70eNwvgP9FOuhbZ1oAJG31dE', // Get actual macOS API key from Firebase Console → Project Settings → macOS apps
    appId: '1:387032593007:android:6ddd689db4a22fd2d0939a', // Get actual macOS app ID from Firebase Console
    messagingSenderId: '387032593007',
    projectId: 'neurolearn-f9f54',
    storageBucket: 'neurolearn.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz1p7Zo70eNwvgP9FOuhbZ1oAJG31dE', // Get actual Windows API key from Firebase Console → Project Settings → Windows apps
    appId: '1:387032593007:android:6ddd689db4a22fd2d0939a', // Get actual Windows app ID from Firebase Console
    messagingSenderId: '387032593007',
    projectId: 'neurolearn-f9f54',
    authDomain: 'neurolearn.firebaseapp.com',
    storageBucket: 'neurolearn.appspot.com',
  );
}
